### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by strideynet** [krystal/guvnor#1]
Tasks are specified inside a service file:

```yaml
tasks:
  console:
    command: ["bin/rails", "console"]
    interactive: true

  migrate:
    command: ["bin/rake", "db:migrate"]

  notifySlack:
    image: slack:21.3.4
    env:
      SLACK_CHANNEL: '#labs'
      SLACK_MESSAGE: "Do something {.Host}"
```

They can override the image used, or use the defaults configured for the service. They can be manually executed via the CLI, and will eventually be possible to be configured on deployment hooks.

It should be possible for some tasks to be interactive (e.g we connect to the users TTY to the running task similar to running a docker command with `-it`)
