### ISSUE TITLE
Service deployment hooks

### ISSUE THREAD

**Issue by strideynet** [krystal/guvnor#2]
Depends on #1 being completed.

It should be possible to configure a series of tasks to run before and after the deployment of a service.

```yaml
callbacks:
  preDeployment: [migrate]
  postDeployment: [notifySlack]
 ```
