### ISSUE TITLE
Command based ready checks

### ISSUE THREAD

**Issue by strideynet** [krystal/guvnor#33]
At the moment we only support HTTP based ready checks, which limits the kinds of services people can host on the platform.

We should aim to also support a command style ready check which executes **within** the container being checked (rather than within it's own container):

```yaml
readyCheck:
    frequency: 2
    maximum: 30
    command:
      command: ["stat" "/ready.txt"]
      expectedExitCode: 0
```
