### ISSUE TITLE
Ready checks

### ISSUE THREAD

**Issue by strideynet** [krystal/guvnor#4]
We should introduce ready checks to processes, so we can ensure that the new deployment is up and healthy before transitioning traffic to it.

This should be configured in the process section of the service config like so:
```yaml
    readyChecks:
      frequency: 2
      timeout: 5
      maximum: 30
      http: # You would have either http OR command in an actual configuration
        expectedStatus: 200
        path: /login
        headers:
          - name: Host
            value: identity.k.io
      command:
        command: ["stat" "/ready.txt"]
        expectedExitCode: 0
```

For now, we only need to support a HTTP check and a command based check. This should cover all bases.
